version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: elt_postgres
    environment:
      POSTGRES_DB: telco
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - ./data:/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      retries: 5

  metabase:
    image: metabase/metabase
    container_name: elt_metabase
    ports:
      - "3000:3000"

  airflow:
    image: apache/airflow:2.7.2
    container_name: elt_airflow
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://user:pass@postgres/telco
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./sql:/data/sql
    ports:
      - "8080:8080"
    command: >
      bash -c "airflow db init &&
               airflow users create --username airflow --firstname airflow --lastname airflow --role Admin --email admin@example.com --password airflow &&
               airflow scheduler & airflow webserver"
